# Generated by Django 5.2 on 2026-06-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='English Name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم العربي')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی ویدیو',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای ویدیو',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='English Title')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='العنوان العربي')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیح فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='English Description')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف العربي')),
                ('source_type', models.CharField(choices=[('upload', 'آپلود مستقیم'), ('embed', 'لینک خارجی')], default='embed', max_length=10, verbose_name='نوع منبع')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فایل ویدیو')),
                ('platform', models.CharField(blank=True, choices=[('', '—'), ('youtube', 'یوتیوب'), ('aparat', 'آپارات'), ('vimeo', 'ویمئو'), ('other', 'سایر')], default='', max_length=10, verbose_name='پلتفرم')),
                ('embed_url', models.URLField(blank=True, verbose_name='URL تعبیه')),
                ('embed_code', models.TextField(blank=True, verbose_name='کد تعبیه')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='تصویر بند انگشتی')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.videocategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['-published_at', 'sort_order'],
            },
        ),
    ]
