# Generated by Django 5.2 on 2026-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevideo',
            name='embed_url',
        ),
        migrations.AlterField(
            model_name='sitevideo',
            name='embed_code',
            field=models.TextField(blank=True, help_text='کد &lt;iframe&gt; را از صفحه ویدیو کپی کنید: یوتیوب ← اشتراک\u200cگذاری ← جاسازی | آپارات ← اشتراک\u200cگذاری ← کد تعبیه (گزینه iframe)', verbose_name='کد iframe'),
        ),
        migrations.AlterField(
            model_name='sitevideo',
            name='source_type',
            field=models.CharField(choices=[('upload', 'آپلود مستقیم'), ('embed', 'ویدیو خارجی (iframe)')], default='embed', max_length=10, verbose_name='نوع منبع'),
        ),
    ]
