# Generated by Django 5.2 on 2026-06-21 11:03

import imagekit.models.fields
import utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_embed_url_rename_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevideo',
            name='file_path',
            field=models.FileField(blank=True, help_text='حداکثر ۵۰ MB — توصیه: ویدیو را در آپارات آپلود کنید و از کد embed استفاده نمایید', null=True, upload_to='videos/', validators=[utils.image_validators.VideoSizeValidator(50)], verbose_name='فایل ویدیو'),
        ),
        migrations.AlterField(
            model_name='sitevideo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='حداکثر ۵ MB — به\u200cصورت خودکار به ۶۴۰×۳۶۰ و WebP تبدیل می\u200cشود', null=True, upload_to='videos/thumbnails/', validators=[utils.image_validators.FileSizeValidator(5)], verbose_name='تصویر بند انگشتی'),
        ),
    ]
