# Generated by Django 5.2 on 2026-06-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان العربي')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='تصویر کاور')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO فارسی')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, verbose_name='SEO Title EN')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO عربي')),
                ('meta_description_fa', models.CharField(blank=True, max_length=165, verbose_name='توضیح SEO فارسی')),
                ('meta_description_en', models.CharField(blank=True, max_length=165, verbose_name='SEO Description EN')),
                ('meta_description_ar', models.CharField(blank=True, max_length=165, verbose_name='وصف SEO عربي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم\u200cها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان العربي')),
                ('alt_fa', models.CharField(blank=True, max_length=200, verbose_name='Alt فارسی')),
                ('alt_en', models.CharField(blank=True, max_length=200, verbose_name='Alt EN')),
                ('alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Alt عربي')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.album', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
