# Generated by Django 5.2 on 2026-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=80, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='English Name')),
                ('name_ar', models.CharField(blank=True, max_length=80, verbose_name='الاسم العربي')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تگ گالری',
                'verbose_name_plural': 'تگ\u200cهای گالری',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان العربي')),
                ('description_fa', models.CharField(blank=True, max_length=300, verbose_name='توضیح فارسی')),
                ('description_en', models.CharField(blank=True, max_length=300, verbose_name='English Description')),
                ('description_ar', models.CharField(blank=True, max_length=300, verbose_name='الوصف العربي')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('alt_fa', models.CharField(blank=True, max_length=200, verbose_name='Alt فارسی')),
                ('alt_en', models.CharField(blank=True, max_length=200, verbose_name='Alt EN')),
                ('alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Alt عربي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='images', to='gallery.gallerytag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
