# Generated by Django 5.2 on 2026-06-21 11:03

import imagekit.models.fields
import utils.image_validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerytag_remove_image_album_galleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='حداکثر ۱۰ MB — به\u200cصورت خودکار به حداکثر ۱۶۰۰×۱۲۰۰ و WebP تبدیل می\u200cشود', upload_to='gallery/', validators=[utils.image_validators.FileSizeValidator(10)], verbose_name='تصویر'),
        ),
    ]
