# Generated by Django 5.2 on 2026-06-21 11:03

import imagekit.models.fields
import utils.image_validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='حداکثر ۵ MB — به\u200cصورت خودکار به حداکثر ۶۰۰×۶۰۰ و WebP تبدیل می\u200cشود', null=True, upload_to='team/', validators=[utils.image_validators.FileSizeValidator(5)], verbose_name='تصویر'),
        ),
    ]
