# Generated by Django 5.2 on 2026-06-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('office', 'خدمات مطب'), ('surgery', 'جراحی')], max_length=10, verbose_name='نوع')),
                ('name_fa', models.CharField(max_length=150, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='English Name')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم العربي')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمات',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان العربي')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیح فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='English Description')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف العربي')),
                ('icon_class', models.CharField(blank=True, max_length=60, verbose_name='آیکون CSS')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO فارسی')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, verbose_name='SEO Title EN')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO عربي')),
                ('meta_description_fa', models.CharField(blank=True, max_length=165, verbose_name='توضیح SEO فارسی')),
                ('meta_description_en', models.CharField(blank=True, max_length=165, verbose_name='SEO Description EN')),
                ('meta_description_ar', models.CharField(blank=True, max_length=165, verbose_name='وصف SEO عربي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
