# Generated by Django 5.2 on 2026-06-21 11:03

import imagekit.models.fields
import utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceitem_summary_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='description_ar',
            field=models.CharField(blank=True, help_text='الحد الأقصى ٢٥٠ حرفًا — يظهر في صفحة الخدمات', max_length=250, verbose_name='الوصف — عربي'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='حداکثر ۸ MB — به\u200cصورت خودکار فشرده و به WebP تبدیل می\u200cشود', null=True, upload_to='services/', validators=[utils.image_validators.FileSizeValidator(8)], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='summary_ar',
            field=models.CharField(blank=True, help_text='الحد الأقصى ٩٠ حرفًا — يظهر في بطاقات الصفحة الرئيسية', max_length=90, verbose_name='الملخص — عربي'),
        ),
    ]
