# Generated by Django 5.2 on 2026-06-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'مدیر ارشد'), ('editor', 'ویرایشگر'), ('author', 'نویسنده'), ('viewer', 'بازدیدکننده')], default='viewer', max_length=20, verbose_name='نقش')),
                ('bio_fa', models.TextField(blank=True, verbose_name='بیوگرافی فارسی')),
                ('bio_en', models.TextField(blank=True, verbose_name='English Bio')),
                ('bio_ar', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربری',
                'verbose_name_plural': 'پروفایل\u200cهای کاربری',
            },
        ),
    ]
