# Generated by Django 5.2 on 2026-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='برای ورود با شماره موبایل — مثال: 09013434195', max_length=20, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
