# Generated by Django 5.2.1 on 2026-06-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='عنوان فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='English Title')),
                ('name_ar', models.CharField(max_length=100, verbose_name='العنوان العربي')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='English Title')),
                ('title_ar', models.CharField(max_length=255, verbose_name='العنوان العربي')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('summary_fa', models.TextField(blank=True, verbose_name='خلاصه فارسی')),
                ('summary_en', models.TextField(blank=True, verbose_name='English Summary')),
                ('summary_ar', models.TextField(blank=True, verbose_name='الملخص العربي')),
                ('content_fa', models.TextField(verbose_name='محتوا فارسی')),
                ('content_en', models.TextField(verbose_name='English Content')),
                ('content_ar', models.TextField(verbose_name='المحتوى العربي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر شاخص')),
                ('author', models.CharField(default='دکتر وحید عبدالرحیمی', max_length=100, verbose_name='نویسنده')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
