# Generated by Django 5.2 on 2026-06-15 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=165, verbose_name='وصف SEO عربي'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=165, verbose_name='SEO Description EN'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_fa',
            field=models.CharField(blank=True, max_length=165, verbose_name='توضیح SEO فارسی'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO عربي'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO Title EN'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_fa',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO فارسی'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
