# Generated by Django 5.2 on 2026-06-15 16:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='المحتوى العربي'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='English Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا فارسی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='ابعاد توصیه\u200cشده: ۱۲۰۰×۶۷۵ پیکسل (نسبت ۱۶:۹) — فرمت: JPG یا WebP — حداکثر حجم: ۵۰۰ کیلوبایت', null=True, upload_to='blog/', verbose_name='تصویر شاخص'),
        ),
    ]
