# Generated by Django 5.2 on 2026-06-16 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content_ar_alter_post_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='متن نظر')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية')], default='fa', max_length=2, verbose_name='زبان')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['created_at'],
            },
        ),
    ]
