# Generated by Django 5.2 on 2026-06-21 11:03

import imagekit.models.fields
import utils.image_validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='حداکثر ۸ MB — به\u200cصورت خودکار به حداکثر ۱۲۰۰×۸۰۰ و WebP تبدیل می\u200cشود', null=True, upload_to='blog/', validators=[utils.image_validators.FileSizeValidator(8)], verbose_name='تصویر شاخص'),
        ),
    ]
