# Generated by Django 5.2 on 2026-06-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='English Title')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='العنوان العربي')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'افتخار پزشک',
                'verbose_name_plural': 'افتخارات پزشک',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English Name')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم العربي')),
                ('address_fa', models.TextField(blank=True, verbose_name='آدرس فارسی')),
                ('address_en', models.TextField(blank=True, verbose_name='English Address')),
                ('address_ar', models.TextField(blank=True, verbose_name='العنوان العربي')),
                ('city_fa', models.CharField(default='تهران', max_length=100, verbose_name='شهر فارسی')),
                ('city_en', models.CharField(default='Tehran', max_length=100, verbose_name='English City')),
                ('city_ar', models.CharField(default='طهران', max_length=100, verbose_name='المدينة العربية')),
                ('phone_1', models.CharField(blank=True, max_length=30, verbose_name='تلفن اول')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='تلفن دوم')),
                ('schedule_fa', models.TextField(blank=True, verbose_name='ساعت کاری فارسی')),
                ('schedule_en', models.TextField(blank=True, verbose_name='English Schedule')),
                ('schedule_ar', models.TextField(blank=True, verbose_name='جدول المواعيد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinics/', verbose_name='تصویر')),
                ('map_url', models.URLField(blank=True, verbose_name='لینک نقشه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مطب/کلینیک',
                'verbose_name_plural': 'مطب\u200cها/کلینیک\u200cها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_fa', models.CharField(max_length=200, verbose_name='مدرک فارسی')),
                ('degree_en', models.CharField(blank=True, max_length=200, verbose_name='English Degree')),
                ('degree_ar', models.CharField(blank=True, max_length=200, verbose_name='الدرجة العلمية')),
                ('institution_fa', models.CharField(max_length=200, verbose_name='مؤسسه فارسی')),
                ('institution_en', models.CharField(blank=True, max_length=200, verbose_name='English Institution')),
                ('institution_ar', models.CharField(blank=True, max_length=200, verbose_name='المؤسسة العربية')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تحصیلات پزشک',
                'verbose_name_plural': 'تحصیلات پزشک',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fa', models.TextField(verbose_name='سوال فارسی')),
                ('question_en', models.TextField(blank=True, verbose_name='English Question')),
                ('question_ar', models.TextField(blank=True, verbose_name='السؤال العربي')),
                ('answer_fa', models.TextField(verbose_name='پاسخ فارسی')),
                ('answer_en', models.TextField(blank=True, verbose_name='English Answer')),
                ('answer_ar', models.TextField(blank=True, verbose_name='الجواب العربي')),
                ('category', models.CharField(default='general', max_length=60, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('home_hero', 'اسلایدر صفحه اصلی'), ('page_hero', 'هدر صفحات داخلی')], default='home_hero', max_length=20, verbose_name='موقعیت')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('caption_fa', models.CharField(blank=True, max_length=255, verbose_name='کپشن فارسی')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='English Caption')),
                ('caption_ar', models.CharField(blank=True, max_length=255, verbose_name='التسمية التوضيحية')),
                ('alt_fa', models.CharField(blank=True, max_length=200, verbose_name='Alt فارسی')),
                ('alt_en', models.CharField(blank=True, max_length=200, verbose_name='Alt EN')),
                ('alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Alt عربي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنرهای سایت',
                'ordering': ['location', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('group_name', models.CharField(max_length=60, verbose_name='گروه')),
                ('label_fa', models.CharField(max_length=150, verbose_name='برچسب فارسی')),
                ('value_fa', models.TextField(blank=True, verbose_name='مقدار فارسی')),
                ('value_en', models.TextField(blank=True, verbose_name='مقدار انگلیسی')),
                ('value_ar', models.TextField(blank=True, verbose_name='مقدار عربی')),
                ('type', models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن بلند'), ('image', 'تصویر'), ('boolean', 'بله/خیر'), ('number', 'عدد'), ('url', 'لینک')], default='text', max_length=20, verbose_name='نوع')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['group_name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام کامل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية')], default='fa', max_length=2, verbose_name='زبان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='English Name')),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='الاسم العربي')),
                ('content_fa', models.TextField(verbose_name='نظر فارسی')),
                ('content_en', models.TextField(blank=True, verbose_name='English Content')),
                ('content_ar', models.TextField(blank=True, verbose_name='المحتوى العربي')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز (۱-۵)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
            ],
            options={
                'verbose_name': 'نظر بیمار',
                'verbose_name_plural': 'نظرات بیماران',
                'ordering': ['-created_at'],
            },
        ),
    ]
