# Generated by Django 5.2 on 2026-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorclinic',
            name='image',
            field=models.ImageField(blank=True, help_text='ابعاد توصیه\u200cشده: ۸۰۰×۶۰۰ پیکسل — فرمت: JPG یا PNG — حداکثر حجم: ۳۰۰ کیلوبایت', null=True, upload_to='clinics/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(help_text='اسلایدر صفحه اصلی: ۱۹۲۰×۸۰۰ پیکسل — هدر صفحات داخلی: ۱۹۲۰×۵۰۰ پیکسل — فرمت: JPG یا WebP — حداکثر حجم: ۱ مگابایت', upload_to='banners/', verbose_name='تصویر'),
        ),
    ]
