# Generated by Django 5.2 on 2026-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctorclinic_image_alter_sitebanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.URLField(blank=True, verbose_name='واتس\u200cاپ')),
                ('youtube', models.URLField(blank=True, verbose_name='یوتیوب')),
                ('aparat', models.URLField(blank=True, verbose_name='آپارات')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
            ],
            options={
                'verbose_name': 'لینک\u200cهای شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه اجتماعی',
            },
        ),
    ]
