# Generated by Django 5.2 on 2026-06-21 11:03

import imagekit.models.fields
import utils.image_validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesetting_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['group_name', 'key'], 'verbose_name': 'آمار نمایشی', 'verbose_name_plural': 'اعداد و آمار نمایشی سایت'},
        ),
        migrations.AlterField(
            model_name='doctorclinic',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='حداکثر ۸ MB — به\u200cصورت خودکار به حداکثر ۱۲۰۰×۹۰۰ و WebP تبدیل می\u200cشود', null=True, upload_to='clinics/', validators=[utils.image_validators.FileSizeValidator(8)], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='حداکثر ۱۰ MB — به\u200cصورت خودکار به حداکثر ۱۹۲۰×۹۰۰ و WebP تبدیل می\u200cشود', upload_to='banners/', validators=[utils.image_validators.FileSizeValidator(10)], verbose_name='تصویر'),
        ),
    ]
