# Generated by Django 5.2 on 2026-06-21 14:56

import imagekit.models.fields
import utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_sitesetting_options_alter_doctorclinic_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='حداکثر ۸ MB — نمای بیرونی ساختمان', upload_to='building/', validators=[utils.image_validators.FileSizeValidator(8)], verbose_name='تصویر')),
                ('caption_fa', models.CharField(blank=True, max_length=200, verbose_name='توضیح فارسی')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='English Caption')),
                ('caption_ar', models.CharField(blank=True, max_length=200, verbose_name='التسمية العربية')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'عکس ساختمان / نمای بیرونی',
                'verbose_name_plural': 'عکس\u200cهای ساختمان / نمای بیرونی',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicInteriorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='حداکثر ۸ MB — تصاویر داخل مطب برای نمایش در صفحه اصلی', upload_to='clinic_interior/', validators=[utils.image_validators.FileSizeValidator(8)], verbose_name='تصویر')),
                ('caption_fa', models.CharField(blank=True, max_length=200, verbose_name='توضیح فارسی')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='English Caption')),
                ('caption_ar', models.CharField(blank=True, max_length=200, verbose_name='التسمية العربية')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'عکس داخل مطب',
                'verbose_name_plural': 'عکس\u200cهای داخل مطب (صفحه اصلی)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('profile', 'تصویر پروفایل — صفحه درباره ما (بالا)'), ('biography', 'تصویر بیوگرافی — صفحه درباره ما (پایین)'), ('surgery', 'تصویر جراحی — صفحه خدمات جراحی')], max_length=20, unique=True, verbose_name='نوع')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='حداکثر ۸ MB — فرمت WebP — حداکثر ۹۰۰×۹۰۰', upload_to='doctor_photos/', validators=[utils.image_validators.FileSizeValidator(8)], verbose_name='تصویر')),
                ('alt_fa', models.CharField(blank=True, max_length=200, verbose_name='Alt فارسی')),
                ('alt_en', models.CharField(blank=True, max_length=200, verbose_name='Alt EN')),
                ('alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Alt عربي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عکس دکتر',
                'verbose_name_plural': 'عکس\u200cهای دکتر',
            },
        ),
        migrations.CreateModel(
            name='SiteBannerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنرهای سایت',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.sitebanner',),
        ),
    ]
